# Generated by Django 6.1 on 2026-09-02 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('action_type', models.CharField(choices=[('MANUAL', 'Manual Adjustment'), ('ORDER', 'Order Fulfillment'), ('RESTOCK', 'Restock/Purchase'), ('RETURN', 'Customer Return'), ('POS', 'POS Sale')], default='MANUAL', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Order ID or Transaction ID', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='inventory.stocklevel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
