databases:
  - name: aura-db
    databaseName: aura_db
    user: aura_user
    plan: free

services:
  - type: web
    name: aura-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aura-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DJANGO_ENV
        value: production
      - key: ALLOWED_HOSTS
        value: "aura-backend.onrender.com,localhost"
    plan: free
