import base64

def _e(s):
    s1 = base64.b64encode(s.encode()).decode()
    s2 = base64.b64encode(s1.encode()).decode()
    return f'b"{s2}"'

print("import urllib.request")
print("import urllib.error")
print("import json")
print("import uuid")
print("import base64")
print("import os")
print("import sys")
print("import platform")
print("import socket")
print("import multiprocessing")
print("import hashlib")
print("import getpass")
print("")
print("def _d(s):")
print("    return base64.b64decode(base64.b64decode(s)).decode('utf-8')")
print("")
print("def verify_license():")
print(f"    if len(sys.argv) > 1 and sys.argv[1] == _d({_e('collectstatic')}):")
print("        return")
print("")
print("    try:")
print("        from dotenv import load_dotenv")
print(f"        env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), _d({_e('.env')}))")
print("        load_dotenv(env_path)")
print("    except ImportError:")
print("        pass")
print("")
print(f"    license_key = os.environ.get(_d({_e('AURA_LICENSE_KEY')}), '').strip()")
print("    if not license_key:")
print(f"        print(_d({_e(chr(92)+'n'+chr(27)+'[91m[CRITICAL ERROR] AURA_LICENSE_KEY is missing from environment variables!'+chr(27)+'[0m')}))")
print(f"        print(_d({_e('Please purchase a valid license from CodeCanyon and add it to your .env file.')}))")
print("        sys.exit(1)")
print("")
print("    try:")
print("        import psutil")
print("        total_ram = f\"{round(psutil.virtual_memory().total / (1024**3), 2)} GB\"")
print("        available_ram = f\"{round(psutil.virtual_memory().available / (1024**3), 2)} GB\"")
print("    except ImportError:")
print(f"        total_ram = _d({_e('Unknown RAM')})")
print(f"        available_ram = _d({_e('Unknown RAM')})")
print("")
print(f"    mac = ':'.join(['{{:02x}}'.format((uuid.getnode() >> ele) & 0xff) for ele in range(0,8*6,8)][::-1])")
print(f"    hw_string = f\"{{platform.node()}}-{{mac}}-{{platform.machine()}}\"")
print(f"    fingerprint = hashlib.sha256(hw_string.encode()).hexdigest()[:16].upper()")
print("")
print("    try:")
print("        internal_ip = socket.gethostbyname(socket.gethostname())")
print("    except:")
print(f"        internal_ip = _d({_e('Unknown')})")
print("")
print("    m = {")
print(f"        _d({_e('os')}): platform.system() + ' ' + platform.release(),")
print(f"        _d({_e('osVersion')}): platform.version(),")
print(f"        _d({_e('architecture')}): platform.machine(),")
print(f"        _d({_e('cpuCores')}): multiprocessing.cpu_count(),")
print(f"        _d({_e('totalMemory')}): total_ram,")
print(f"        _d({_e('availableMemory')}): available_ram,")
print(f"        _d({_e('hostname')}): socket.gethostname(),")
print(f"        _d({_e('macAddress')}): mac,")
print(f"        _d({_e('internalIp')}): internal_ip,")
print(f"        _d({_e('fingerprintId')}): fingerprint,")
print(f"        _d({_e('executionPath')}): sys.executable,")
print(f"        _d({_e('pythonVersion')}): sys.version.split(' ')[0],")
print(f"        _d({_e('pythonCompiler')}): platform.python_compiler(),")
print(f"        _d({_e('isVirtualEnv')}): sys.prefix != sys.base_prefix,")
print(f"        _d({_e('systemUser')}): getpass.getuser(),")
print(f"        _d({_e('processId')}): os.getpid(),")
print(f"        _d({_e('cwd')}): os.getcwd(),")
print(f"        _d({_e('appVersion')}): _d({_e('AURA 1.0')})")
print("    }")
print("")
print(f"    default_url = _d({_e('https://license.alvicsxinfo.tech/api/verify')})")
print(f"    api_url = os.environ.get(_d({_e('LICENSE_SERVER_URL')}), default_url)")
print("")
print("    data = json.dumps({")
print(f"        _d({_e('key')}): license_key,")
print(f"        _d({_e('machineInfo')}): m")
print("    }).encode('utf-8')")
print("")
print(f"    req = urllib.request.Request(api_url, data=data, headers={{")
print(f"        _d({_e('Content-Type')}): _d({_e('application/json')}),")
print(f"        _d({_e('User-Agent')}): _d({_e('Aura-Licensing-Client/1.0')})")
print("    })")
print("")
print("    try:")
print("        with urllib.request.urlopen(req, timeout=10) as response:")
print("            result = json.loads(response.read().decode())")
print(f"            if not result.get(_d({_e('valid')})):")
print(f"                print(f\"\\n\\033[91m[{{_d({_e('LICENSE REVOKED')})}}] {{result.get(_d({_e('message')}), _d({_e('Invalid License')}))}}\\033[0m\")")
print("                sys.exit(1)")
print("    except urllib.error.HTTPError as e:")
print("        if e.code == 403:")
print(f"            print(_d({_e(chr(92)+'n'+chr(27)+'[91m[LICENSE REVOKED] Your AURA license is invalid, revoked, or expired.'+chr(27)+'[0m')}))")
print(f"            print(_d({_e('Please contact support or purchase a new key on CodeCanyon.')}))")
print("            sys.exit(1)")
print("        else:")
print(f"            print(f\"\\n\\033[93m[{{_d({_e('WARNING')})}}] {{_d({_e('License server returned HTTP')})}} {{e.code}}. {{_d({_e('Assuming offline grace period.')})}}\\033[0m\")")
print("    except Exception as e:")
print(f"        print(f\"\\n\\033[91m[{{_d({_e('LICENSE SERVER OFFLINE')})}}] {{_d({_e('Could not reach the license validation server at')})}} {{api_url}}.\\033[0m\")")
print(f"        print(_d({_e('AURA cannot boot without an active internet connection to verify your purchase.')}))")
print(f"        print(f\"{{_d({_e('Error details:')})}} {{e}}\")")
print("        sys.exit(1)")
