import asyncio
from playwright.async_api import async_playwright

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        
        await page.goto('http://localhost:8000/login/')
        await page.fill('input[name="username"]', 'alvics')
        await page.fill('input[name="password"]', '12345678')
        await page.click('button[type="submit"]')
        await page.wait_for_load_state('networkidle')
        await page.goto('http://localhost:8000/dashboard/')
        await page.wait_for_load_state('networkidle')
        
        # Get all classes on body and their actual CSS rules applied
        rules = await page.evaluate("""
            (() => {
                const el = document.body;
                const rules = window.getMatchedCSSRules ? window.getMatchedCSSRules(el) : [];
                let res = [];
                // Fallback since getMatchedCSSRules is deprecated in modern Chrome
                // Let's just find the rule for background-color explicitly using getComputedStyle
                // and then dump all style tags generated by Tailwind
                let styleTags = Array.from(document.querySelectorAll('style')).map(s => s.innerHTML);
                return styleTags;
            })()
        """)
        
        for idx, tag in enumerate(rules):
            if "bg-theme-bg-base" in tag:
                print(f"FOUND IN STYLE TAG {idx}:")
                # find the line containing bg-theme-bg-base
                for line in tag.split('}'):
                    if "bg-theme-bg-base" in line:
                        print(line + "}")
        
        await browser.close()

asyncio.run(main())
