# Generated by Django 6.1 on 2026-08-19 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTryOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_image', models.ImageField(upload_to='try_ons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_confidence_score', models.FloatField(blank=True, help_text='0.0 to 1.0', null=True)),
                ('purchased_after_try_on', models.BooleanField(default=False)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='try_ons', to='catalog.productvariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='try_ons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
