# Generated by Django 6.1 on 2026-08-19 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_consumerprofile_base_photo_userphotoprofile'),
        ('catalog', '0002_product_is_vto_ready_product_slug_garmentaiprofile'),
        ('fitting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualtryon',
            name='purchased_after_try_on',
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='photo_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='try_ons', to='accounts.userphotoprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='provider',
            field=models.CharField(choices=[('MOCK', 'Mock Provider'), ('STABLE_DIFFUSION', 'Stable Diffusion API')], default='MOCK', max_length=50),
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='selected_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.size'),
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATING', 'Validating Inputs'), ('ANALYZING', 'Analyzing Photos'), ('PROCESSING', 'Processing Generation'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='virtualtryon',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to='tryons/outputs/'),
        ),
    ]
