# Generated by Django 6.1 on 2026-08-20 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_brand_color_brand_product_is_active_and_more'),
        ('fitting', '0003_virtualtryon_session_key_alter_virtualtryon_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualtryon',
            name='photo_profile',
        ),
        migrations.RemoveField(
            model_name='virtualtryon',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='virtualtryon',
            name='user',
        ),
        migrations.AlterField(
            model_name='virtualtryon',
            name='provider',
            field=models.CharField(choices=[('MOCK', 'Mock Provider'), ('STABLE_DIFFUSION', 'Stable Diffusion API'), ('TRYON_DIFFUSION', 'TryOn Diffusion Engine')], default='TRYON_DIFFUSION', max_length=50),
        ),
        migrations.CreateModel(
            name='FitPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('body_shape', models.CharField(blank=True, choices=[('HOURGLASS', 'Hourglass'), ('PEAR', 'Pear'), ('APPLE', 'Apple'), ('RECTANGLE', 'Rectangle'), ('INVERTED_TRIANGLE', 'Inverted Triangle')], max_length=20, null=True)),
                ('fit_preference', models.CharField(choices=[('TIGHT', 'Tight Fit'), ('REGULAR', 'Regular Fit'), ('LOOSE', 'Loose/Oversized Fit')], default='REGULAR', max_length=20)),
                ('gender_preference', models.CharField(blank=True, choices=[('MASCULINE', 'Masculine'), ('FEMININE', 'Feminine'), ('ANDROGYNOUS', 'Androgynous'), ('NEUTRAL', 'Neutral')], max_length=20, null=True)),
                ('chest_cm', models.FloatField(blank=True, null=True)),
                ('waist_cm', models.FloatField(blank=True, null=True)),
                ('hips_cm', models.FloatField(blank=True, null=True)),
                ('inseam_cm', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fit_passport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VTOPhotoVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vto/vault/')),
                ('pose_type', models.CharField(choices=[('FRONT', 'Front'), ('SIDE', 'Side'), ('FULL', 'Full Body')], default='FRONT', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(blank=True, help_text='0.0 to 1.0', null=True)),
                ('validation_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fitting.fitpassport')),
            ],
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='base_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='try_ons', to='fitting.vtophotovault'),
        ),
        migrations.CreateModel(
            name='VTOProductAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('FLAT_LAY', 'Flat Lay'), ('GHOST_MANNEQUIN', 'Ghost Mannequin'), ('MASK', 'Mask')], max_length=20)),
                ('image', models.ImageField(upload_to='vto/product_assets/')),
                ('readiness_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vto_assets', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='VTOSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vto_sessions', to='fitting.fitpassport')),
            ],
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='try_ons', to='fitting.vtosession'),
        ),
    ]
