# Generated by Django 6.1 on 2026-08-20 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_brand_color_brand_product_is_active_and_more'),
        ('fitting', '0004_remove_virtualtryon_photo_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualWardrobeLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('try_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitting.virtualtryon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_looks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VTOGarment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_type', models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('SHOES', 'Shoes'), ('OUTERWEAR', 'Outerwear'), ('ACCESSORY', 'Accessory')], default='TOP', max_length=20)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant')),
                ('selected_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.size')),
                ('try_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='fitting.virtualtryon')),
            ],
        ),
    ]
