# Generated by Django 6.1 on 2026-08-20 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_brand_color_brand_product_is_active_and_more'),
        ('fitting', '0005_virtualwardrobelook_vtogarment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VTOProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('SHOES', 'Shoes'), ('OUTERWEAR', 'Outerwear'), ('ACCESSORY', 'Accessory')], default='TOP', max_length=20)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant')),
                ('selected_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.size')),
                ('try_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='fitting.virtualtryon')),
            ],
        ),
        migrations.DeleteModel(
            name='VTOGarment',
        ),
    ]
