# Generated by Django 6.1 on 2026-08-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0006_vtoproduct_delete_vtogarment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAvatarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary')], max_length=20)),
                ('image', models.ImageField(upload_to='vto/avatars/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
