# Generated by Django 6.1 on 2026-08-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0007_aiavatarmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualtryon',
            name='progress_percent',
            field=models.IntegerField(default=0, help_text='Real-time generation progress 0-100'),
        ),
    ]
