# Generated by Django 6.1 on 2026-08-21 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0008_virtualtryon_progress_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiavatarmodel',
            name='image',
            field=models.ImageField(upload_to='vto/avatars/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='fitpassport',
            name='chest_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitpassport',
            name='height_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitpassport',
            name='hips_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitpassport',
            name='inseam_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitpassport',
            name='waist_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='fitpassport',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='virtualtryon',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to='tryons/outputs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='vtophotovault',
            name='image',
            field=models.ImageField(upload_to='vto/vault/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='vtoproductassets',
            name='image',
            field=models.ImageField(upload_to='vto/product_assets/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
    ]
