# Generated by Django 6.1 on 2026-08-22 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0009_alter_aiavatarmodel_image_alter_fitpassport_chest_cm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fitpassport',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='User has consented to body data processing for virtual try-on'),
        ),
        migrations.AddField(
            model_name='fitpassport',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when consent was granted', null=True),
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='qa_notes',
            field=models.TextField(blank=True, help_text='Internal reviewer notes'),
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='qa_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='qa_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tryons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='virtualtryon',
            name='qa_status',
            field=models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Review')], default='UNREVIEWED', max_length=20),
        ),
    ]
