# Generated by Django 6.1 on 2026-08-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_collection_image_and_more'),
        ('fitting', '0010_fitpassport_consent_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualtryon',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='try_ons', to='catalog.productvariant'),
        ),
    ]
