# Generated by Django 6.1 on 2026-08-19 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='The ultimate AI fitting room for modern fashion brands', max_length=255)),
                ('hero_subheadline', models.TextField(default='Stop dealing with returns due to poor sizing. Aura uses state-of-the-art Generative AI and Computer Vision to let your customers try on your entire catalog virtually.')),
                ('hero_primary_cta', models.CharField(default='Start your Store', max_length=50)),
                ('hero_secondary_cta', models.CharField(default='Brand Login', max_length=50)),
                ('demo_title', models.CharField(default='Experience it live', max_length=255)),
                ('demo_subtitle', models.CharField(default='Trusted Brands', max_length=255)),
                ('footer_text', models.CharField(default='© 2026 Aura Virtual Try-On. All rights reserved.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Config',
                'verbose_name_plural': 'Landing Page Configs',
            },
        ),
        migrations.CreateModel(
            name='LandingPageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('BRAND', 'Brand Owners'), ('SHOPPER', 'Shoppers / End Users')], max_length=20)),
                ('icon_class', models.CharField(help_text="FontAwesome class e.g., 'fa-solid fa-chart-line'", max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.landingpageconfig')),
            ],
            options={
                'ordering': ['audience', 'display_order'],
            },
        ),
    ]
