# Generated by Django 6.1 on 2026-08-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_footersection_page_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AURA.', max_length=100)),
                ('support_email', models.EmailField(default='support@aura.com', max_length=254)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('primary_color', models.CharField(default='#4f46e5', help_text='Hex code (e.g., #4f46e5)', max_length=20)),
                ('secondary_color', models.CharField(default='#1e293b', help_text='Hex code (e.g., #1e293b)', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('stripe_public_key', models.CharField(blank=True, max_length=255)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=255)),
                ('stripe_webhook_secret', models.CharField(blank=True, max_length=255)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=255)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=255)),
                ('twilio_sender_number', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
