# Generated by Django 6.1 on 2026-08-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_code', models.CharField(help_text='e.g. ESEWA, KHALTI, PATHAO', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('PAYMENT', 'Payments'), ('SHIPPING', 'Shipping & Logistics'), ('MARKETING', 'Marketing & Analytics'), ('OTHER', 'Other Add-ons')], max_length=20)),
                ('description', models.TextField()),
                ('icon_html', models.TextField(help_text="HTML for the icon, e.g. <i class='fa-solid fa-wallet'></i>")),
                ('icon_color_hex', models.CharField(default='#6366f1', help_text='e.g. #60BB46 for eSewa', max_length=10)),
                ('icon_bg_hex', models.CharField(default='#e0e7ff', help_text='e.g. #60BB4620 for light green bg', max_length=10)),
                ('is_active_globally', models.BooleanField(default=True, help_text='Turn off to disable this integration for all stores')),
                ('requires_merchant_id', models.BooleanField(default=False)),
                ('requires_api_key', models.BooleanField(default=False)),
                ('requires_api_secret', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
