# Generated by Django 6.1 on 2026-08-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=10),
        ),
    ]
