# Generated by Django 6.1 on 2026-08-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_globalsettings_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsetting',
            name='google_review_url',
            field=models.URLField(blank=True, help_text='Direct link for Google Reviews', null=True),
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='wifi_network_name',
            field=models.CharField(blank=True, help_text='WiFi SSID for store', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
