# Generated by Django 6.1 on 2026-08-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_brandsetting_google_review_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsetting',
            name='pos_thermal_paper_size',
            field=models.CharField(default='80mm', help_text='e.g. 58mm, 80mm', max_length=20),
        ),
    ]
