# Generated by Django 6.1 on 2026-08-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_brandsetting_pos_thermal_paper_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsetting',
            name='show_tax_on_receipt',
            field=models.BooleanField(default=True, help_text='Display Tax/PAN on printed receipts and customer display'),
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='tax_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='tax_id_type',
            field=models.CharField(blank=True, help_text='e.g. PAN, VAT, GST', max_length=20, null=True),
        ),
    ]
