# Generated by Django 6.1 on 2026-08-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_brandsetting_show_tax_on_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='stripe_environment',
            field=models.CharField(choices=[('DEMO', 'Demo Mode (Bypass Stripe)'), ('TEST', 'Stripe Test Mode'), ('LIVE', 'Stripe Live Mode')], default='DEMO', help_text='Demo bypasses Stripe completely. Test/Live use the keys below.', max_length=10),
        ),
    ]
