# Generated by Django 6.1 on 2026-08-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_globalsettings_stripe_environment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='stripe_public_key',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='stripe_secret_key',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='stripe_webhook_secret',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='stripe_live_public_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='stripe_live_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='stripe_live_webhook_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='stripe_test_public_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='stripe_test_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='stripe_test_webhook_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='stripe_environment',
            field=models.CharField(choices=[('TEST', 'Stripe Test Mode'), ('LIVE', 'Stripe Live Mode')], default='TEST', help_text='Toggle between Test Mode and Live Production Mode.', max_length=10),
        ),
    ]
