# Generated by Django 6.1 on 2026-08-21 05:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_globalsettings_stripe_public_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='brandsetting',
            name='primary_color',
            field=models.CharField(default='#000000', help_text='Hex color code', max_length=7, validators=[django.core.validators.RegexValidator(message='Invalid hex code.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='brandsetting',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage (e.g., 13.00 for 13%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='primary_color',
            field=models.CharField(default='#4f46e5', help_text='Hex code (e.g., #4f46e5)', max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid hex code.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='secondary_color',
            field=models.CharField(default='#1e293b', help_text='Hex code (e.g., #1e293b)', max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid hex code.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='site_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='platformintegration',
            name='icon_bg_hex',
            field=models.CharField(default='#e0e7ff', help_text='e.g. #60BB4620 for light green bg', max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid hex code.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='platformintegration',
            name='icon_color_hex',
            field=models.CharField(default='#6366f1', help_text='e.g. #60BB46 for eSewa', max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid hex code.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTHER', 'Other')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, help_text='Stored data changes or relevant metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Audit Log',
                'verbose_name_plural': 'System Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
