# Generated by Django 6.1 on 2026-08-21 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_brandsetting_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformintegration',
            name='icon_bg_hex',
        ),
        migrations.RemoveField(
            model_name='platformintegration',
            name='icon_color_hex',
        ),
        migrations.RemoveField(
            model_name='platformintegration',
            name='icon_html',
        ),
        migrations.AddField(
            model_name='platformintegration',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload logo for the integration', null=True, upload_to='integrations/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
    ]
