# Generated by Django 6.1 on 2026-08-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_platformintegration_icon_bg_hex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='replicate_api_key',
            field=models.CharField(blank=True, help_text='Required if using Replicate API', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='replicate_model_version',
            field=models.CharField(default='cuiaxi/kolors-virtual-try-on', help_text='e.g. cuiaxi/kolors-virtual-try-on', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='vto_engine',
            field=models.CharField(choices=[('replicate', 'Cloud API: Replicate (Recommended)'), ('mobile_vton', 'Local: MobileVTON (Requires GPU)'), ('tryon_diffusion', 'Local: TryOn Diffusion (Requires GPU)'), ('mock', 'Mock Engine (Testing Only)')], default='replicate', help_text='Select which AI engine to use for Virtual Try-On.', max_length=50),
        ),
    ]
