# Generated by Django 6.1 on 2026-08-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_globalsettings_replicate_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='vto_engine',
            field=models.CharField(choices=[('replicate', 'Cloud API: Replicate (Recommended)'), ('mobile_vton', 'Local: MobileVTON (Requires GPU)'), ('cat_vton', 'Local: CatVTON (Requires GPU)'), ('mock', 'Mock Engine (Testing Only)')], default='replicate', help_text='Select which AI engine to use for Virtual Try-On.', max_length=50),
        ),
    ]
