# Generated by Django 6.1 on 2026-08-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_globalsettings_vto_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='replicate_model_version',
            field=models.CharField(default='cuuupid/idm-vton', help_text='e.g. cuuupid/idm-vton', max_length=255),
        ),
    ]
