# Generated by Django 6.1 on 2026-08-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_globalsettings_replicate_model_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='hf_api_token',
            field=models.CharField(blank=True, help_text='Your Hugging Face Access Token (Required if space is private or duplicated)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='hf_space_id',
            field=models.CharField(blank=True, default='Kwai-Kolors/Kolors-Virtual-Try-On', help_text='e.g. Kwai-Kolors/Kolors-Virtual-Try-On or your duplicated space ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='vto_engine',
            field=models.CharField(choices=[('local', 'Local API (ComfyUI / Stable Diffusion)'), ('replicate', 'Cloud API: Replicate'), ('huggingface', 'Cloud API: Hugging Face Spaces')], default='local', help_text='Select which AI engine to use for Virtual Try-On.', max_length=20),
        ),
    ]
