# Generated by Django 6.1 on 2026-08-23 15:59

from django.db import migrations


def add_stripe_integration(apps, schema_editor):
    PlatformIntegration = apps.get_model('core', 'PlatformIntegration')
    PlatformIntegration.objects.get_or_create(
        provider_code='STRIPE',
        defaults={
            'name': 'Stripe Payments',
            'category': 'PAYMENT',
            'description': 'Accept credit cards and global payments securely via Stripe.',
            'is_active_globally': True,
            'requires_api_key': True,
            'requires_api_secret': True,
            'requires_merchant_id': False,
        }
    )

def remove_stripe_integration(apps, schema_editor):
    PlatformIntegration = apps.get_model('core', 'PlatformIntegration')
    PlatformIntegration.objects.filter(provider_code='STRIPE').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_globalsettings_hf_api_token_and_more'),
    ]

    operations = [
        migrations.RunPython(add_stripe_integration, remove_stripe_integration),
    ]
