# Generated by Django 6.1 on 2026-08-23 16:34

from django.db import migrations


def add_integrations(apps, schema_editor):
    PlatformIntegration = apps.get_model('core', 'PlatformIntegration')
    
    integrations = [
        # Marketing & Analytics
        {
            'provider_code': 'TIKTOK_PIXEL',
            'name': 'TikTok Pixel',
            'category': 'MARKETING',
            'description': 'Track conversions, page views, and optimize TikTok ad campaigns.',
            'is_active_globally': True,
            'requires_api_key': True,  # Pixel ID
            'requires_api_secret': False,
            'requires_merchant_id': False,
        },
        {
            'provider_code': 'KLAVIYO',
            'name': 'Klaviyo',
            'category': 'MARKETING',
            'description': 'Advanced email marketing and SMS automation for e-commerce.',
            'is_active_globally': True,
            'requires_api_key': True,  # Public API Key
            'requires_api_secret': True, # Private API Key
            'requires_merchant_id': False,
        },
        {
            'provider_code': 'HOTJAR',
            'name': 'Hotjar',
            'category': 'MARKETING',
            'description': 'Session recordings and heatmaps to understand user behavior.',
            'is_active_globally': True,
            'requires_api_key': True,  # Site ID
            'requires_api_secret': False,
            'requires_merchant_id': False,
        },
        # Customer Support
        {
            'provider_code': 'TAWK_TO',
            'name': 'Tawk.to Live Chat',
            'category': 'MARKETING', # Using marketing for widgets
            'description': 'Free live chat widget to communicate with visitors in real-time.',
            'is_active_globally': True,
            'requires_api_key': True,  # Widget property ID
            'requires_api_secret': False,
            'requires_merchant_id': False,
        },
        {
            'provider_code': 'WHATSAPP_WIDGET',
            'name': 'WhatsApp Floating Widget',
            'category': 'MARKETING',
            'description': 'Add a floating WhatsApp button for direct customer support.',
            'is_active_globally': True,
            'requires_api_key': False,
            'requires_api_secret': False,
            'requires_merchant_id': True, # Phone Number
        },
        # Payments
        {
            'provider_code': 'PAYPAL',
            'name': 'PayPal Checkout',
            'category': 'PAYMENT',
            'description': 'Accept payments securely via PayPal.',
            'is_active_globally': True,
            'requires_api_key': True,  # Client ID
            'requires_api_secret': True, # Client Secret
            'requires_merchant_id': False,
        },
        {
            'provider_code': 'RAZORPAY',
            'name': 'Razorpay',
            'category': 'PAYMENT',
            'description': 'The most popular payment gateway for Indian businesses.',
            'is_active_globally': True,
            'requires_api_key': True,  # Key ID
            'requires_api_secret': True, # Key Secret
            'requires_merchant_id': False,
        },
        # Shipping
        {
            'provider_code': 'SHIPROCKET',
            'name': 'Shiprocket',
            'category': 'SHIPPING',
            'description': 'Automated e-commerce shipping and courier allocation.',
            'is_active_globally': True,
            'requires_api_key': True,  # API Token
            'requires_api_secret': False,
            'requires_merchant_id': False,
        },
        {
            'provider_code': 'DHL',
            'name': 'DHL Express',
            'category': 'SHIPPING',
            'description': 'Premium international shipping and fulfillment.',
            'is_active_globally': True,
            'requires_api_key': True,
            'requires_api_secret': True,
            'requires_merchant_id': True,
        }
    ]
    
    for intg_data in integrations:
        PlatformIntegration.objects.get_or_create(
            provider_code=intg_data['provider_code'],
            defaults=intg_data
        )

def remove_integrations(apps, schema_editor):
    PlatformIntegration = apps.get_model('core', 'PlatformIntegration')
    codes = ['TIKTOK_PIXEL', 'KLAVIYO', 'HOTJAR', 'TAWK_TO', 'WHATSAPP_WIDGET', 'PAYPAL', 'RAZORPAY', 'SHIPROCKET', 'DHL']
    PlatformIntegration.objects.filter(provider_code__in=codes).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_stripe_platform_integration'),
    ]

    operations = [
        migrations.RunPython(add_integrations, remove_integrations),
    ]
