# Generated by Django 5.1.2 on 2026-08-23 22:36

from django.db import migrations

def add_advanced_integrations(apps, schema_editor):
    PlatformIntegration = apps.get_model('core', 'PlatformIntegration')
    
    integrations = [
        # Payments
        {
            'name': 'Klarna (Buy Now Pay Later)',
            'provider_code': 'KLARNA',
            'category': 'PAYMENT',
            'description': 'Let customers split their purchases into 4 interest-free payments.',
            'requires_api_key': False,
            'requires_api_secret': False,
            'requires_merchant_id': False,
            'is_active_globally': True,
        },
        {
            'name': 'Afterpay',
            'provider_code': 'AFTERPAY',
            'category': 'PAYMENT',
            'description': 'Offer Buy Now, Pay Later capabilities to increase conversion rates.',
            'requires_api_key': False,
            'requires_api_secret': False,
            'requires_merchant_id': False,
            'is_active_globally': True,
        },
        # Marketing/Comms
        {
            'name': 'Twilio SMS',
            'provider_code': 'TWILIO',
            'category': 'MARKETING',
            'description': 'Send automated SMS order confirmations and tracking updates.',
            'requires_api_key': False,
            'requires_api_secret': False,
            'requires_merchant_id': False,
            'is_active_globally': True,
        },
        {
            'name': 'SendGrid',
            'provider_code': 'SENDGRID',
            'category': 'MARKETING',
            'description': 'Reliable transactional email delivery for order receipts.',
            'requires_api_key': False,
            'requires_api_secret': False,
            'requires_merchant_id': False,
            'is_active_globally': True,
        },
        # Other
        {
            'name': 'Zapier',
            'provider_code': 'ZAPIER',
            'category': 'OTHER',
            'description': 'Connect Aura to 5000+ apps. Trigger workflows on new orders.',
            'requires_api_key': False,
            'requires_api_secret': False,
            'requires_merchant_id': False,
            'is_active_globally': True,
        }
    ]
    
    for item in integrations:
        # Avoid duplicates just in case
        if not PlatformIntegration.objects.filter(provider_code=item['provider_code']).exists():
            PlatformIntegration.objects.create(**item)

def remove_advanced_integrations(apps, schema_editor):
    PlatformIntegration = apps.get_model('core', 'PlatformIntegration')
    codes = ['KLARNA', 'AFTERPAY', 'TWILIO', 'SENDGRID', 'ZAPIER']
    PlatformIntegration.objects.filter(provider_code__in=codes).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_extra_platform_integrations'),
    ]

    operations = [
        migrations.RunPython(add_advanced_integrations, remove_advanced_integrations),
    ]
