# Generated by Django 6.1 on 2026-08-24 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_advanced_integrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Short description for the blog listing page')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('author_name', models.CharField(default='Aura Team', max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='quote',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_title',
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='blog_subtitle',
            field=models.CharField(default='News, tips, and insights about fashion tech.', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='blog_title',
            field=models.CharField(default='Latest from our blog', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='contact_address',
            field=models.CharField(default='123 Fashion Ave, NY 10001', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='contact_email',
            field=models.EmailField(default='contact@auravto.com', max_length=254),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='contact_phone',
            field=models.CharField(default='+1 (555) 123-4567', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='contact_subtitle',
            field=models.CharField(default="We'd love to hear from you.", max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='contact_title',
            field=models.CharField(default='Get in touch', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='features_subtitle',
            field=models.CharField(default='Everything you need to run a successful virtual fitting room.', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='features_title',
            field=models.CharField(default='Why choose Aura', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='testimonials_subtitle',
            field=models.CharField(default='Trusted by leading fashion brands worldwide.', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='testimonials_title',
            field=models.CharField(default='What our clients say', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, help_text='1 to 5 stars'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role',
            field=models.CharField(default='Customer', help_text='e.g., CEO at Fashion Brand', max_length=100),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='hf_space_id',
            field=models.CharField(blank=True, default='fashn-ai/fashn-vton-1.5', help_text='e.g. fashn-ai/fashn-vton-1.5 or your duplicated space ID', max_length=255, null=True),
        ),
    ]
