# Generated by Django 6.1 on 2026-08-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='social_facebook',
            field=models.URLField(blank=True, help_text='Facebook Page URL', null=True),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='social_instagram',
            field=models.URLField(blank=True, help_text='Instagram Profile URL', null=True),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='social_linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn Page URL', null=True),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='social_twitter',
            field=models.URLField(blank=True, help_text='X/Twitter Profile URL', null=True),
        ),
    ]
