# Generated by Django 6.1 on 2026-08-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_landingpageconfig_social_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='cta_button_text',
            field=models.CharField(default='Start your free trial', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='cta_subtitle',
            field=models.CharField(default='Join the top fashion brands using Aura to reduce returns and increase conversion.', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='cta_title',
            field=models.CharField(default='Ready to transform your store?', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='faq_subtitle',
            field=models.CharField(default='Everything you need to know about Aura.', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='faq_title',
            field=models.CharField(default='Frequently Asked Questions', max_length=255),
        ),
    ]
