# Generated by Django 6.1 on 2026-08-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_faqitem_landingpageconfig_cta_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='e.g. fa-brands fa-shopify', max_length=100)),
                ('icon_color', models.CharField(default='text-slate-800', help_text='e.g. text-[#95bf47] or text-indigo-500', max_length=50)),
                ('hover_color', models.CharField(default='group-hover:text-slate-900', help_text='e.g. group-hover:text-emerald-500', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. 99.9%, 50M+', max_length=50)),
                ('label', models.CharField(help_text='e.g. Uptime SLA, Try-Ons Generated', max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
