# Generated by Django 6.1 on 2026-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_integrationplatform_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='email_api_key',
            field=models.CharField(blank=True, help_text='API Key for Resend, SendGrid, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='email_provider',
            field=models.CharField(choices=[('smtp', 'Custom SMTP'), ('resend', 'Resend'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('ses', 'Amazon SES')], default='smtp', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='smtp_encryption',
            field=models.CharField(choices=[('tls', 'TLS (Recommended)'), ('ssl', 'SSL'), ('none', 'None')], default='tls', max_length=10),
        ),
    ]
