# Generated by Django 6.1 on 2026-08-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_globalsettings_email_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='email_api_key',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='mailgun_api_key',
            field=models.CharField(blank=True, help_text='API Key for Mailgun', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='resend_api_key',
            field=models.CharField(blank=True, help_text='API Key for Resend', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='sendgrid_api_key',
            field=models.CharField(blank=True, help_text='API Key for SendGrid', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ses_access_key_id',
            field=models.CharField(blank=True, help_text='AWS Access Key ID for SES', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ses_region',
            field=models.CharField(blank=True, default='us-east-1', help_text='AWS Region (e.g. us-east-1)', max_length=50),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ses_secret_access_key',
            field=models.CharField(blank=True, help_text='AWS Secret Access Key for SES', max_length=255),
        ),
    ]
