# Generated by Django 6.1 on 2026-08-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_notificationcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('welcome', 'Welcome / Registration'), ('order_confirmation', 'Order Confirmation'), ('signup_verification', 'Signup Verification / OTP'), ('billing_invoice', 'Billing / Invoice'), ('password_reset', 'Password Reset')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(help_text='HTML content of the email. Supports Django template tags like {{ user.first_name }}')),
                ('is_active', models.BooleanField(default=True, help_text='If disabled, the system will use the default hardcoded template.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
