# Generated by Django 6.1 on 2026-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_blogpost_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='systememailtemplate',
            name='event_type',
            field=models.CharField(choices=[('welcome', 'Welcome / Registration'), ('signup_verification', 'Signup Verification / OTP'), ('password_reset', 'Password Reset Request'), ('password_changed', 'Password Changed Successfully'), ('account_locked', 'Account Locked'), ('two_factor_enabled', '2FA Enabled'), ('two_factor_disabled', '2FA Disabled'), ('new_login_detected', 'New Device Login'), ('email_changed', 'Email Address Changed'), ('account_deletion', 'Account Deletion Request'), ('subscription_success', 'Subscription Started/Success'), ('subscription_canceled', 'Subscription Canceled'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_expiring', 'Subscription Expiring Soon'), ('payment_failed', 'Payment Failed'), ('billing_invoice', 'Billing / Invoice Available'), ('payment_method_expiring', 'Payment Method Expiring'), ('plan_upgraded', 'Plan Upgraded'), ('plan_downgraded', 'Plan Downgraded'), ('trial_ending_soon', 'Free Trial Ending Soon'), ('order_confirmation', 'Order Confirmation'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_canceled', 'Order Canceled'), ('order_refunded', 'Order Refunded'), ('order_partially_refunded', 'Order Partially Refunded'), ('out_for_delivery', 'Order Out for Delivery'), ('abandoned_cart', 'Abandoned Cart Reminder'), ('digital_download_ready', 'Digital Product Ready'), ('gift_card_issued', 'Gift Card Issued'), ('store_created', 'New Store Created'), ('domain_connected', 'Custom Domain Connected'), ('domain_disconnected', 'Custom Domain Disconnected'), ('staff_invitation', 'Staff Member Invited'), ('staff_role_changed', 'Staff Role Changed'), ('new_order_received', 'New Order Received (Admin Alert)'), ('low_inventory_alert', 'Low Inventory Alert'), ('payout_processed', 'Payout Processed'), ('payout_failed', 'Payout Failed'), ('report_generated', 'Export/Report Generation Complete'), ('support_ticket_created', 'Support Ticket Created'), ('support_ticket_replied', 'Support Ticket Replied'), ('support_ticket_closed', 'Support Ticket Closed'), ('newsletter_subscribed', 'Newsletter Subscription Confirmed'), ('product_review_request', 'Request for Product Review'), ('customer_welcome', 'Customer Account Welcome (Store level)'), ('back_in_stock', 'Back in Stock Alert'), ('price_drop', 'Price Drop Alert'), ('promo_code_issued', 'Special Promo Code Issued'), ('custom_campaign', 'Custom Marketing Campaign')], max_length=50, unique=True),
        ),
    ]
