# Generated by Django 6.1 on 2026-09-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_emaillog_alter_systememailtemplate_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='email_sender_address',
            field=models.EmailField(blank=True, help_text='The email address to send outgoing system emails from (e.g. noreply@yourdomain.com). If blank, Support Email is used. Must be a verified domain for API providers.', max_length=254),
        ),
    ]
