# Define the HTML content for all 50 system templates

def get_h2(title, emoji=""):
    return f'<h2 style="color: #0f172a; margin-top: 0; margin-bottom: 20px; font-size: 24px;">{title} {emoji}</h2>'

def get_p(text):
    return f'<p style="color: #334155; font-size: 16px; line-height: 1.6; margin-bottom: 24px;">{text}</p>'

def get_button(text, url="{{ url|default:'#' }}"):
    return f'<div style="text-align: center; margin: 30px 0;"><a href="{url}" style="display: inline-block; background-color: #0f172a; color: #ffffff; text-decoration: none; font-weight: bold; font-size: 16px; padding: 16px 32px; border-radius: 8px;">{text}</a></div>'

def get_box(content):
    return f'<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom: 30px;"><tr><td style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px;">{content}</td></tr></table>'

TEMPLATE_SEEDS = {
    # Account & Security
    'welcome': (
        'Welcome to {{ platform_settings.site_name|default:"Aura" }}!',
        get_h2('Welcome to Aura, {{ user.first_name|default:"there" }}!', '🎉') +
        get_p('We\'re absolutely thrilled to have you on board. You\'re now equipped with the ultimate tools to manage your fashion brand.') +
        get_box('<h3 style="margin-top: 0; color: #0f172a; font-size: 18px;">What\'s Next?</h3><p style="color: #475569; font-size: 15px; margin-bottom: 0;">Explore premium features, set up your profile, and experience our platform like never before.</p>') +
        get_button('Get Started', '{{ login_url }}')
    ),
    'signup_verification': (
        'Verify your email address',
        get_h2('Verify Your Email', '✉️') +
        get_p('Hi {{ user.first_name|default:"there" }}, please use the verification code below to verify your email address.') +
        get_box('<p style="margin: 0; text-align: center; color: #0f172a; font-size: 36px; font-weight: 800; letter-spacing: 8px;">{{ otp_code }}</p>') +
        get_p('This code is valid for 15 minutes. If you did not request this, please ignore this email.')
    ),
    'password_reset': (
        'Password Reset Request',
        get_h2('Password Reset', '🔒') +
        get_p('Hi {{ user.first_name|default:"there" }}, we received a request to reset your password.') +
        get_button('Reset Password', '{{ reset_url }}') +
        get_p('If you did not request this, you can safely ignore this email.')
    ),
    'password_changed': (
        'Password Changed Successfully',
        get_h2('Password Updated', '✅') +
        get_p('Hi {{ user.first_name|default:"there" }}, your password was successfully changed.') +
        get_p('If you did not perform this action, please contact support immediately.')
    ),
    'account_locked': (
        'Security Alert: Account Locked',
        get_h2('Account Locked', '⚠️') +
        get_p('Hi {{ user.first_name|default:"there" }}, your account has been temporarily locked due to multiple failed login attempts.') +
        get_button('Unlock Account', '{{ unlock_url }}')
    ),
    'two_factor_enabled': (
        '2FA Successfully Enabled',
        get_h2('Two-Factor Authentication Enabled', '🔐') +
        get_p('Hi {{ user.first_name|default:"there" }}, two-factor authentication (2FA) has been successfully enabled on your account. Your account is now more secure.') +
        get_box('<p style="margin: 0; color: #475569; font-size: 15px;">You will now be required to enter a security code generated by your authenticator app each time you sign in.</p>')
    ),
    'two_factor_disabled': (
        'Security Alert: 2FA Disabled',
        get_h2('Two-Factor Authentication Disabled', '🔓') +
        get_p('Hi {{ user.first_name|default:"there" }}, two-factor authentication (2FA) has been disabled on your account.') +
        get_p('If you did not make this change, please secure your account and contact support immediately.')
    ),
    'new_login_detected': (
        'New Login Detected on your Account',
        get_h2('New Device Login', '📱') +
        get_p('Hi {{ user.first_name|default:"there" }}, we noticed a new login to your account from an unrecognized device.') +
        get_box('<p style="margin: 0 0 8px 0; color: #475569; font-size: 15px;"><strong>Device:</strong> {{ device_name }}</p><p style="margin: 0 0 8px 0; color: #475569; font-size: 15px;"><strong>Location:</strong> {{ location }}</p><p style="margin: 0; color: #475569; font-size: 15px;"><strong>IP Address:</strong> {{ ip_address }}</p>') +
        get_p('If this was you, you can safely ignore this email. If not, please change your password immediately.')
    ),
    'email_changed': (
        'Your Email Address was Changed',
        get_h2('Email Address Updated', '📧') +
        get_p('Hi {{ user.first_name|default:"there" }}, the email address associated with your account was recently changed.') +
        get_box('<p style="margin: 0 0 8px 0; color: #475569; font-size: 15px;"><strong>Old Email:</strong> {{ old_email }}</p><p style="margin: 0; color: #475569; font-size: 15px;"><strong>New Email:</strong> {{ new_email }}</p>') +
        get_p('If you did not request this change, contact support immediately.')
    ),
    'account_deletion': (
        'Account Deletion Request Scheduled',
        get_h2('Account Deletion Requested', '🗑️') +
        get_p('Hi {{ user.first_name|default:"there" }}, we have received a request to permanently delete your account.') +
        get_box('<p style="margin: 0; color: #475569; font-size: 15px;">Your account will be fully deleted on <strong>{{ deletion_date }}</strong>. You will lose access to all your data.</p>') +
        get_button('Cancel Deletion', '{{ cancel_deletion_url }}')
    ),

    # Billing & Subscriptions
    'subscription_success': (
        'Subscription Confirmed',
        get_h2('Subscription Successful', '🚀') +
        get_p('Hi {{ user.first_name|default:"there" }}, your subscription to the <strong>{{ plan_name }}</strong> plan is now active.') +
        get_box('<h3 style="margin: 0 0 16px 0; color: #0f172a; font-size: 18px;">Plan Details</h3><p style="margin: 0 0 8px 0; color: #475569; font-size: 15px;"><strong>Plan:</strong> {{ plan_name }}</p><p style="margin: 0; color: #475569; font-size: 15px;"><strong>Next Billing Date:</strong> {{ next_billing_date }}</p>')
    ),
    'subscription_canceled': (
        'Subscription Canceled',
        get_h2('Subscription Canceled', '😔') +
        get_p('Hi {{ user.first_name|default:"there" }}, your subscription to the <strong>{{ plan_name }}</strong> plan has been canceled.') +
        get_box('<p style="margin: 0; color: #475569; font-size: 15px;">You will continue to have access to your plan features until <strong>{{ end_date }}</strong>.</p>') +
        get_button('Reactivate Subscription', '{{ reactivate_url }}')
    ),
    'subscription_renewed': (
        'Your Subscription has Renewed',
        get_h2('Subscription Renewed', '🔄') +
        get_p('Hi {{ user.first_name|default:"there" }}, your <strong>{{ plan_name }}</strong> subscription has been successfully renewed.') +
        get_box('<p style="margin: 0 0 8px 0; color: #475569; font-size: 15px;"><strong>Amount Charged:</strong> ${{ amount }}</p><p style="margin: 0; color: #475569; font-size: 15px;"><strong>Next Renewal:</strong> {{ next_billing_date }}</p>')
    ),
    'subscription_expiring': (
        'Action Required: Subscription Expiring Soon',
        get_h2('Subscription Expiring Soon', '⏳') +
        get_p('Hi {{ user.first_name|default:"there" }}, your subscription to the <strong>{{ plan_name }}</strong> plan will expire in <strong>{{ days_left }} days</strong>.') +
        get_button('Renew Now', '{{ billing_url }}')
    ),
    'payment_failed': (
        'Payment Failed - Action Required',
        get_h2('Payment Failed', '❌') +
        get_p('Hi {{ user.first_name|default:"there" }}, we were unable to process your recent payment of <strong>${{ amount }}</strong>.') +
        get_button('Update Payment Method', '{{ billing_url }}')
    ),
    'billing_invoice': (
        'New Invoice Available',
        get_h2('Your Invoice is Ready', '🧾') +
        get_p('Hi {{ user.first_name|default:"Customer" }}, a new invoice has been generated for your recent subscription or platform usage.') +
        get_box('<p style="margin: 0 0 8px 0; color: #64748b; font-size: 14px;">Amount Due</p><p style="margin: 0; color: #0f172a; font-size: 28px; font-weight: 800;">${{ invoice_amount }}</p><p style="margin: 12px 0 0 0; color: #475569; font-size: 14px;">Due Date: <strong>{{ due_date }}</strong></p>') +
        get_button('Download Invoice PDF', '{{ invoice_url }}')
    ),
    'payment_method_expiring': (
        'Your Payment Method is Expiring',
        get_h2('Payment Method Expiring', '💳') +
        get_p('Hi {{ user.first_name|default:"there" }}, the credit card ending in <strong>{{ card_last4 }}</strong> is expiring soon.') +
        get_p('Please update your payment method to ensure your subscription remains active without interruption.') +
        get_button('Update Payment Method', '{{ billing_url }}')
    ),
    'plan_upgraded': (
        'Plan Upgraded Successfully!',
        get_h2('You\'re Upgraded!', '🎉') +
        get_p('Hi {{ user.first_name|default:"there" }}, your plan has been successfully upgraded to <strong>{{ plan_name }}</strong>.') +
        get_box('<p style="margin: 0; color: #475569; font-size: 15px;">You now have immediate access to all the advanced features included in your new tier!</p>') +
        get_button('Explore Features', '{{ dashboard_url }}')
    ),
    'plan_downgraded': (
        'Plan Downgrade Confirmed',
        get_h2('Plan Downgraded', '📉') +
        get_p('Hi {{ user.first_name|default:"there" }}, your plan has been downgraded to <strong>{{ plan_name }}</strong>. This change will take effect at the end of your current billing cycle.') +
        get_p('If this was a mistake, you can always upgrade back to your previous plan.')
    ),
    'trial_ending_soon': (
        'Your Free Trial is Ending Soon',
        get_h2('Trial Ending Soon', '⏱️') +
        get_p('Hi {{ user.first_name|default:"there" }}, we hope you\'ve enjoyed exploring our platform! Your free trial will expire in <strong>{{ days_left }} days</strong>.') +
        get_box('<p style="margin: 0; color: #475569; font-size: 15px;">To ensure uninterrupted access to all features, please upgrade to a paid plan before your trial ends.</p>') +
        get_button('Upgrade Plan', '{{ billing_url }}')
    ),

    # Orders & Fulfillment
    'order_confirmation': (
        'Order Confirmation #{{ order_id }}',
        get_h2('Thank You For Your Order!', '🛍️') +
        get_p('Hi {{ customer_name }}, we\'ve received your order <strong>#{{ order_id }}</strong> and we\'re getting it ready for you.') +
        get_box('<h3 style="margin: 0 0 16px 0; color: #0f172a; font-size: 18px;">Order Summary</h3><p style="margin: 0 0 8px 0; color: #475569; font-size: 15px;"><strong>Total Amount:</strong> ${{ order_total }}</p><p style="margin: 0; color: #475569; font-size: 15px;"><strong>Shipping Address:</strong><br>{{ shipping_address }}</p>') +
        get_button('View Order Status', '{{ order_url }}')
    ),
    'order_shipped': (
        'Your Order is on the way!',
        get_h2('Order Shipped', '🚚') +
        get_p('Hi {{ customer_name }}, good news! Your order <strong>#{{ order_id }}</strong> has been shipped.') +
        get_box('<h3 style="margin: 0 0 16px 0; color: #0f172a; font-size: 18px;">Tracking Information</h3><p style="margin: 0 0 8px 0; color: #475569; font-size: 15px;"><strong>Courier:</strong> {{ courier_name }}</p><p style="margin: 0; color: #475569; font-size: 15px;"><strong>Tracking Number:</strong> {{ tracking_number }}</p>') +
        get_button('Track Package', '{{ tracking_url }}')
    ),
    'order_delivered': (
        'Your Order has been Delivered!',
        get_h2('Order Delivered', '📦') +
        get_p('Hi {{ customer_name }}, your order <strong>#{{ order_id }}</strong> has been marked as delivered. We hope you love your items!')
    ),
    'order_canceled': (
        'Order #{{ order_id }} has been Canceled',
        get_h2('Order Canceled', '🚫') +
        get_p('Hi {{ customer_name }}, your order <strong>#{{ order_id }}</strong> has been successfully canceled.') +
        get_p('If your payment had already been processed, a full refund will be issued to your original payment method.')
    ),
    'order_refunded': (
        'Refund Processed for Order #{{ order_id }}',
        get_h2('Refund Processed', '💸') +
        get_p('Hi {{ customer_name }}, a refund of <strong>${{ refund_amount }}</strong> has been processed for your order <strong>#{{ order_id }}</strong>. Please allow 3-5 business days for the funds to appear in your account.')
    ),
    'order_partially_refunded': (
        'Partial Refund Processed for Order #{{ order_id }}',
        get_h2('Partial Refund Issued', '💵') +
        get_p('Hi {{ customer_name }}, a partial refund of <strong>${{ refund_amount }}</strong> has been issued for your order <strong>#{{ order_id }}</strong>.')
    ),
    'out_for_delivery': (
        'Your Order is Out for Delivery Today!',
        get_h2('Out for Delivery', '🏡') +
        get_p('Hi {{ customer_name }}, get ready! Your order <strong>#{{ order_id }}</strong> is currently out for delivery and will arrive today.')
    ),
    'abandoned_cart': (
        'Did you forget something?',
        get_h2('You left items in your cart', '🛒') +
        get_p('Hi {{ customer_name }}, we noticed you left some amazing items in your cart. They are selling out fast, so complete your purchase before they are gone!') +
        get_button('Return to Checkout', '{{ checkout_url }}')
    ),
    'digital_download_ready': (
        'Your Digital Product is Ready for Download',
        get_h2('Download Ready', '📥') +
        get_p('Hi {{ customer_name }}, your digital product from order <strong>#{{ order_id }}</strong> is ready for download.') +
        get_button('Download File', '{{ download_url }}')
    ),
    'gift_card_issued': (
        'You received a Gift Card!',
        get_h2('You received a Gift Card!', '🎁') +
        get_p('Hi {{ customer_name }}, someone special has sent you a gift card valued at <strong>${{ amount }}</strong>.') +
        get_box('<p style="margin: 0; text-align: center; color: #0f172a; font-size: 24px; font-weight: 800; letter-spacing: 4px;">{{ gift_card_code }}</p>') +
        get_button('Start Shopping', '{{ store_url }}')
    ),

    # Store Management & Admin
    'store_created': (
        'Your Store has been Created!',
        get_h2('Store Created Successfully', '🏪') +
        get_p('Hi {{ user.first_name|default:"there" }}, your new store <strong>{{ store_name }}</strong> is officially up and running!') +
        get_button('Go to Dashboard', '{{ dashboard_url }}')
    ),
    'domain_connected': (
        'Custom Domain Connected',
        get_h2('Domain Connected', '🌐') +
        get_p('Great news! Your custom domain <strong>{{ domain_name }}</strong> is now successfully connected to your store.')
    ),
    'domain_disconnected': (
        'Custom Domain Disconnected',
        get_h2('Domain Disconnected', '🔌') +
        get_p('Your custom domain <strong>{{ domain_name }}</strong> has been disconnected from your store.')
    ),
    'staff_invitation': (
        'You have been invited to join a Store',
        get_h2('Staff Invitation', '👋') +
        get_p('Hi there, you have been invited to join the staff team for the store <strong>{{ store_name }}</strong> with the role of <strong>{{ role_name }}</strong>.') +
        get_button('Accept Invitation', '{{ accept_url }}')
    ),
    'staff_role_changed': (
        'Your Staff Role has been Updated',
        get_h2('Role Updated', '🛡️') +
        get_p('Hi {{ user.first_name|default:"there" }}, your role at <strong>{{ store_name }}</strong> has been changed to <strong>{{ new_role }}</strong>.')
    ),
    'new_order_received': (
        'New Order Received!',
        get_h2('New Order Alert', '🔔') +
        get_p('You have received a new order <strong>#{{ order_id }}</strong> worth <strong>${{ order_total }}</strong>.') +
        get_button('View Order Details', '{{ admin_order_url }}')
    ),
    'low_inventory_alert': (
        'Low Inventory Alert',
        get_h2('Low Stock Alert', '⚠️') +
        get_p('The inventory level for <strong>{{ product_name }}</strong> is running low. There are only <strong>{{ stock_left }}</strong> items left in stock.') +
        get_button('Manage Inventory', '{{ inventory_url }}')
    ),
    'payout_processed': (
        'Payout Processed Successfully',
        get_h2('Payout Processed', '💰') +
        get_p('Great news! A payout of <strong>${{ amount }}</strong> has been successfully processed to your linked bank account.') +
        get_p('Please allow up to 3 business days for the funds to clear.')
    ),
    'payout_failed': (
        'Payout Failed',
        get_h2('Payout Failed', '🛑') +
        get_p('We attempted to process a payout of <strong>${{ amount }}</strong> to your account, but it failed.') +
        get_p('Please review your bank details or contact support for assistance.')
    ),
    'report_generated': (
        'Your Report is Ready for Download',
        get_h2('Report Generated', '📊') +
        get_p('The report you requested (<strong>{{ report_name }}</strong>) has finished generating and is ready for download.') +
        get_button('Download Report', '{{ download_url }}')
    ),

    # Support & Marketing
    'support_ticket_created': (
        'Support Ticket Received',
        get_h2('Ticket Created', '🎫') +
        get_p('Hi {{ user.first_name|default:"there" }}, we have successfully received your support ticket (ID: <strong>#{{ ticket_id }}</strong>).') +
        get_box('<p style="margin: 0; color: #475569; font-size: 15px;">Our team is reviewing your request and will get back to you within 24 hours.</p>')
    ),
    'support_ticket_replied': (
        'Update on your Support Ticket',
        get_h2('Ticket Replied', '💬') +
        get_p('Hi {{ user.first_name|default:"there" }}, an agent has replied to your support ticket (ID: <strong>#{{ ticket_id }}</strong>).') +
        get_button('View Reply', '{{ ticket_url }}')
    ),
    'support_ticket_closed': (
        'Support Ticket Closed',
        get_h2('Ticket Closed', '✅') +
        get_p('Hi {{ user.first_name|default:"there" }}, your support ticket (ID: <strong>#{{ ticket_id }}</strong>) has been marked as resolved and closed.') +
        get_p('If you still need assistance, you can reopen the ticket or create a new one.')
    ),
    'newsletter_subscribed': (
        'Welcome to our Newsletter!',
        get_h2('Thanks for Subscribing!', '📰') +
        get_p('You\'re on the list! You will now receive our latest updates, news, and exclusive offers straight to your inbox.')
    ),
    'product_review_request': (
        'How did you like your recent purchase?',
        get_h2('Leave a Review', '⭐') +
        get_p('Hi {{ customer_name }}, we hope you\'re loving your recent purchase of <strong>{{ product_name }}</strong>.') +
        get_p('We would really appreciate it if you could take a moment to leave a review and let us know what you think!') +
        get_button('Write a Review', '{{ review_url }}')
    ),
    'customer_welcome': (
        'Welcome to {{ store_name }}',
        get_h2('Welcome to {{ store_name }}!', '🎉') +
        get_p('Hi {{ customer_name }}, thank you for creating an account with us. We are excited to have you shop with us!') +
        get_button('Start Shopping', '{{ store_url }}')
    ),
    'back_in_stock': (
        'An item is Back in Stock!',
        get_h2('Back in Stock!', '🔥') +
        get_p('Good news! The item you were eyeing (<strong>{{ product_name }}</strong>) is finally back in stock.') +
        get_button('Shop Now', '{{ product_url }}')
    ),
    'price_drop': (
        'Price Drop Alert',
        get_h2('Price Drop!', '📉') +
        get_p('The price for <strong>{{ product_name }}</strong> has just dropped to <strong>${{ new_price }}</strong>!') +
        get_button('View Product', '{{ product_url }}')
    ),
    'promo_code_issued': (
        'A Special Promo Code just for you',
        get_h2('Special Offer!', '🏷️') +
        get_p('Hi {{ customer_name }}, to show our appreciation, here is a special promo code for <strong>{{ discount_amount }} off</strong> your next purchase.') +
        get_box('<p style="margin: 0; text-align: center; color: #0f172a; font-size: 24px; font-weight: 800; letter-spacing: 4px;">{{ promo_code }}</p>') +
        get_button('Shop Now', '{{ store_url }}')
    ),
    'custom_campaign': (
        'A Message from {{ platform_settings.site_name|default:"Aura" }}',
        get_h2('Important Update', '📣') +
        get_p('Hello {{ user.first_name|default:"there" }},') +
        get_box('<p style="margin: 0; color: #475569; font-size: 15px;">{{ custom_message }}</p>')
    ),
}

# Fallback generator for any unlisted events (just in case)
def get_seed_data(event_type):
    if event_type in TEMPLATE_SEEDS:
        return TEMPLATE_SEEDS[event_type]
    
    title = event_type.replace('_', ' ').title()
    subject = f"{title} Notification"
    body = get_h2(title, '🔔') + get_p('Hello {{ user.first_name|default:"there" }},') + get_p(f'This is an automated notification regarding: <strong>{title}</strong>.') + get_box('<p style="margin: 0; color: #475569; font-size: 15px;">Additional details will appear here.</p>')
    return subject, body
