# Generated by Django 6.1 on 2026-08-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, help_text='e.g. ESEWA, KHALTI, MANUAL', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference_id',
            field=models.CharField(blank=True, help_text='Transaction ID from the gateway', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_provider',
            field=models.CharField(blank=True, help_text='e.g. PATHAO_PARCEL, NCM, UPAYA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Consignment ID from the logistics provider', max_length=255, null=True),
        ),
    ]
