# Generated by Django 6.1 on 2026-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_customer_name_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Screenshot of manual/QR payment', null=True, upload_to='payment_proofs/'),
        ),
    ]
