# Generated by Django 6.1 on 2026-08-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_brand_address_brand_description_brand_facebook_url_and_more'),
        ('orders', '0004_order_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Inside Valley, Outside Valley, Nationwide', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Shipping cost for this zone', max_digits=10)),
                ('estimated_days', models.CharField(blank=True, help_text='e.g. 1-2 days, 3-5 days', max_length=50, null=True)),
                ('is_free_above', models.DecimalField(blank=True, decimal_places=2, help_text='Free shipping if order total is above this amount (leave blank for no free threshold)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zones', to='brands.brand')),
            ],
            options={
                'ordering': ['display_order', 'rate'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.shippingzone'),
        ),
    ]
