# Generated by Django 6.1 on 2026-08-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('SENT_TO_COURIER', 'Sent to Courier'), ('COURIER_PROCESSING', 'Courier Processing'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
