# Generated by Django 6.1 on 2026-08-22 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0019_brand_b2b_discount_percent_brand_enable_gift_cards'),
        ('orders', '0012_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='brands.brand'),
        ),
    ]
