# Generated by Django 6.1 on 2026-08-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0019_brand_b2b_discount_percent_brand_enable_gift_cards'),
        ('catalog', '0008_alter_collection_image_and_more'),
        ('orders', '0013_cart_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order'),
        ),
    ]
