# Generated by Django 6.1 on 2026-08-19 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_brand_banner_brand_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID (e.g. price_1N...)', max_length=255, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('try_on_quota', models.IntegerField(default=10000, help_text='Number of try-ons per billing cycle (-1 for unlimited)')),
                ('is_popular', models.BooleanField(default=False)),
                ('features', models.JSONField(default=list, help_text='List of features as JSON strings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='trialing', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('try_ons_used', models.IntegerField(default=0)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='brands.brand')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscriptionplan')),
            ],
        ),
    ]
