# Generated by Django 6.1 on 2026-09-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_subscriptionplan_monthly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_test_price_id',
            field=models.CharField(blank=True, help_text='Stripe Test Price ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Live Price ID', max_length=255, null=True),
        ),
    ]
