# Generated by Django 6.1 on 2026-09-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscriptionplan_stripe_test_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AlterField(
            model_name='brandsubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction / Session ID'),
        ),
    ]
