# Generated by Django 6.1 on 2026-09-02 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_brandsubscription_stripe_customer_id_and_more'),
        ('brands', '0023_alter_storefrontsection_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('canceled', 'Canceled'), ('renewed', 'Renewed')], max_length=20)),
                ('previous_plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('new_plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=255, null=True)),
                ('payment_details', models.JSONField(blank=True, default=dict, help_text='Stores card network, last4, wallet type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='brands.brand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
