# Generated by Django 6.1 on 2026-09-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_subscriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_api_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_b2b_wholesale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_custom_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_custom_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_remove_watermark',
            field=models.BooleanField(default=False),
        ),
    ]
