# Generated by Django 6.1 on 2026-08-19 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_vto_ready_product_slug_garmentaiprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, help_text='e.g., top, bottom, full_body', max_length=100, null=True)),
                ('fit_type', models.CharField(blank=True, help_text='e.g., slim, regular, oversized', max_length=100, null=True)),
                ('material', models.CharField(blank=True, help_text='e.g., cotton, denim, leather', max_length=100, null=True)),
                ('processed_asset', models.ImageField(blank=True, null=True, upload_to='products/ai_assets/processed/')),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending Validation/Processing'), ('COMPLETED', 'AI Ready'), ('FAILED', 'Processing Failed')], default='PENDING', max_length=20)),
                ('ai_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to='catalog.productvariant')),
            ],
        ),
        migrations.DeleteModel(
            name='GarmentAIProfile',
        ),
    ]
