# Generated by Django 6.1 on 2026-08-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_brandintegration'),
        ('catalog', '0004_productimage_productmodelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Null = platform-wide default', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='brands.brand'),
        ),
        migrations.AddField(
            model_name='color',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Null = platform-wide default', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='brands.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Null = platform-wide default', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='brands.brand'),
        ),
        migrations.AddField(
            model_name='size',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Null = platform-wide default', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collections/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='brands.brand')),
                ('products', models.ManyToManyField(blank=True, related_name='collections', to='catalog.product')),
            ],
        ),
    ]
