# Generated by Django 6.1 on 2026-08-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_brand_color_brand_product_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, choices=[('CASUAL', 'Casual'), ('FORMAL', 'Formal'), ('WEDDING', 'Wedding'), ('PARTY', 'Party'), ('OFFICE', 'Office'), ('TRAVEL', 'Travel'), ('ACTIVEWEAR', 'Activewear')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='style_tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.styletag'),
        ),
    ]
