# Generated by Django 6.1 on 2026-08-21 12:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_styletag_product_occasion_product_style_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(help_text='#RRGGBB', max_length=7, validators=[django.core.validators.RegexValidator(message='Invalid hex code.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='productaiprofile',
            name='processed_asset',
            field=models.ImageField(blank=True, null=True, upload_to='products/ai_assets/processed/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='productmodelimage',
            name='image',
            field=models.ImageField(upload_to='product_model_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='sizechartrule',
            name='max_chest_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='sizechartrule',
            name='max_waist_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='sizechartrule',
            name='min_chest_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='sizechartrule',
            name='min_waist_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
