# Generated by Django 6.1 on 2026-08-21 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0013_popupbanner_body_content_popupbanner_headline_and_more'),
        ('catalog', '0007_alter_collection_image_alter_color_hex_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('brand', 'slug')},
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
            ],
        ),
    ]
