# Generated by Django 6.1 on 2026-08-23

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    ProductVariant = apps.get_model('catalog', 'ProductVariant')
    Category = apps.get_model('catalog', 'Category')
    Collection = apps.get_model('catalog', 'Collection')
    
    # Products
    for product in Product.objects.filter(slug__isnull=True) | Product.objects.filter(slug=''):
        base_slug = slugify(product.name) or 'product'
        unique_slug = base_slug
        counter = 1
        while Product.objects.filter(slug=unique_slug).exclude(pk=product.pk).exists():
            unique_slug = f"{base_slug}-{counter}"
            counter += 1
        product.slug = unique_slug
        product.save()

    # Product Variants
    for variant in ProductVariant.objects.filter(slug__isnull=True) | ProductVariant.objects.filter(slug=''):
        base_slug = slugify(f"{variant.product.slug or variant.product.name}-{variant.color.name}-{variant.size.code}")
        unique_slug = base_slug
        counter = 1
        while ProductVariant.objects.filter(slug=unique_slug).exclude(pk=variant.pk).exists():
            unique_slug = f"{base_slug}-{counter}"
            counter += 1
        variant.slug = unique_slug
        variant.save()
        
    # Categories
    for category in Category.objects.filter(slug__isnull=True) | Category.objects.filter(slug=''):
        base_slug = slugify(category.name) or 'category'
        unique_slug = base_slug
        counter = 1
        while Category.objects.filter(slug=unique_slug).exclude(pk=category.pk).exists():
            unique_slug = f"{base_slug}-{counter}"
            counter += 1
        category.slug = unique_slug
        category.save()
        
    # Collections
    for collection in Collection.objects.filter(slug__isnull=True) | Collection.objects.filter(slug=''):
        base_slug = slugify(collection.title) or 'collection'
        unique_slug = base_slug
        counter = 1
        while Collection.objects.filter(slug=unique_slug).exclude(pk=collection.pk).exists():
            unique_slug = f"{base_slug}-{counter}"
            counter += 1
        collection.slug = unique_slug
        collection.save()

class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0009_productvariant_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
