# Generated by Django 6.1 on 2026-08-24 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_populate_all_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Product SEO Meta Description', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma separated keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_og_image',
            field=models.ImageField(blank=True, help_text='OpenGraph Image for social sharing', null=True, upload_to='product_seo/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Product SEO Title (max 150 chars)', max_length=150, null=True),
        ),
    ]
