# Generated by Django 6.1 on 2026-08-19 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerprofile',
            name='base_photo',
        ),
        migrations.CreateModel(
            name='UserPhotoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_photo', models.ImageField(upload_to='users/photo_profiles/original/')),
                ('processed_photo', models.ImageField(blank=True, null=True, upload_to='users/photo_profiles/processed/')),
                ('segmentation_mask', models.ImageField(blank=True, null=True, upload_to='users/photo_profiles/masks/')),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending Validation'), ('VALID', 'Valid for Try-On'), ('INVALID', 'Invalid/Poor Quality')], default='PENDING', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('analysis_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
