# Generated by Django 6.1 on 2026-08-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userphotoprofile_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='chest_cm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
