# Generated by Django 6.1 on 2026-08-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='Used for POS global lookup', max_length=20, null=True),
        ),
    ]
