# Generated by Django 6.1 on 2026-08-21 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_consumerprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerprofile',
            name='chest_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='consumerprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='Used for POS global lookup', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone format.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='consumerprofile',
            name='shoulder_width_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='consumerprofile',
            name='waist_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='userphotoprofile',
            name='original_photo',
            field=models.ImageField(upload_to='users/photo_profiles/original/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='userphotoprofile',
            name='processed_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photo_profiles/processed/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='userphotoprofile',
            name='segmentation_mask',
            field=models.ImageField(blank=True, null=True, upload_to='users/photo_profiles/masks/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
    ]
