# Generated by Django 6.1 on 2026-08-22 08:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_consumerprofile_chest_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name for B2B customers', max_length=200),
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='is_b2b',
            field=models.BooleanField(default=False, help_text='Mark as a B2B / wholesale customer'),
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='store_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available store credit balance', max_digits=10),
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax / VAT registration number', max_length=50),
        ),
    ]
