# Generated by Django 6.1 on 2026-08-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='brand_banners/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active Storefront'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance')], default='ACTIVE', max_length=20),
        ),
    ]
