# Generated by Django 6.1 on 2026-08-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_apikey_mediaasset_webhookendpoint'),
        ('core', '0006_platformintegration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Store API keys, merchant IDs, etc. here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='brands.brand')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_configs', to='core.platformintegration')),
            ],
            options={
                'unique_together': {('brand', 'integration')},
            },
        ),
    ]
