# Generated by Django 6.1 on 2026-08-19 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_brandintegration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_type', models.CharField(help_text='e.g., Fashion & Apparel', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this theme globally')),
                ('template_folder', models.CharField(help_text='Folder name in templates/storefront/ e.g., theme_fashion', max_length=100)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='theme_previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='brands.storetheme'),
        ),
    ]
