# Generated by Django 6.1 on 2026-08-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_storetheme_brand_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, help_text='Short description for the store footer', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='pinterest_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='support_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
