# Generated by Django 6.1 on 2026-08-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_brand_address_brand_description_brand_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='currency_code',
            field=models.CharField(blank=True, help_text='Override global currency (e.g., NPR, USD)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='currency_symbol',
            field=models.CharField(blank=True, help_text='Override global symbol (e.g., Rs., $)', max_length=10, null=True),
        ),
    ]
