# Generated by Django 6.1 on 2026-08-21 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_brand_currency_code_brand_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='banner_cta_link',
            field=models.CharField(blank=True, help_text="URL or section ID for the CTA (e.g. '#collection')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='banner_cta_text',
            field=models.CharField(blank=True, help_text="Text for the call-to-action button (e.g. 'Shop Now')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='banner_subtitle',
            field=models.TextField(blank=True, help_text='Subtitle or description for the banner', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='banner_title',
            field=models.CharField(blank=True, help_text='Main heading for the storefront banner', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='brand_banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='brand',
            name='support_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone format.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(upload_to='brand_media/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg', 'pdf', 'mp4'])]),
        ),
        migrations.AlterField(
            model_name='storetheme',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme_previews/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
    ]
