# Generated by Django 6.1 on 2026-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_brand_banner_cta_link_brand_banner_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='banner_badge_text',
            field=models.CharField(blank=True, help_text="Small badge text in the hero section (e.g. 'Dropping Now')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='banner_secondary_cta_link',
            field=models.CharField(blank=True, help_text='URL for the secondary button', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='banner_secondary_cta_text',
            field=models.CharField(blank=True, help_text="Text for a secondary button (e.g. 'Watch Video')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='top_announcement_text',
            field=models.CharField(blank=True, help_text="Text for the top announcement bar (e.g. 'Free Shipping on all orders')", max_length=200, null=True),
        ),
    ]
