# Generated by Django 6.1 on 2026-08-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_brand_banner_badge_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='footer_copyright_text',
            field=models.CharField(blank=True, help_text='Custom copyright text for the footer', max_length=200, null=True),
        ),
    ]
