# Generated by Django 6.1 on 2026-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_brand_footer_copyright_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center')], default='left', help_text='Alignment of the logo in the storefront header', max_length=10),
        ),
    ]
