# Generated by Django 6.1 on 2026-08-21 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0011_brand_logo_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('banner_type', models.CharField(choices=[('TOP_BAR', 'Top Bar Banner'), ('BOTTOM_POPUP', 'Bottom Popup'), ('MODAL', 'Center Modal')], default='TOP_BAR', max_length=20)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_link', models.CharField(blank=True, max_length=255)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('display_rule', models.CharField(choices=[('ALL_PAGES', 'All Pages'), ('HOMEPAGE_ONLY', 'Homepage Only'), ('SPECIFIC_URL', 'Specific URL Path')], default='ALL_PAGES', max_length=20)),
                ('specific_url', models.CharField(blank=True, help_text='e.g. /shop/', max_length=255)),
                ('delay_seconds', models.IntegerField(default=0, help_text='Show after this many seconds')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup_banners', to='brands.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED', 'Fixed Amount Discount')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage or Fixed Amount', max_digits=10)),
                ('condition', models.CharField(choices=[('NONE', 'No Condition'), ('FIRST_PURCHASE', 'First Purchase Only')], default='NONE', max_length=20)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_uses', models.IntegerField(default=0, help_text='0 for unlimited')),
                ('times_used', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='brands.brand')),
            ],
            options={
                'unique_together': {('brand', 'code')},
            },
        ),
    ]
