# Generated by Django 6.1 on 2026-08-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0012_popupbanner_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupbanner',
            name='body_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='popupbanner',
            name='headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='popupbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/marketing/popups/'),
        ),
    ]
