# Generated by Django 6.1 on 2026-08-22 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0014_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this campaign', max_length=255)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('target_audience', models.CharField(choices=[('SUBSCRIBERS', 'Newsletter Subscribers'), ('CUSTOMERS', 'Registered Customers'), ('BOTH', 'Everyone')], default='SUBSCRIBERS', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent')], default='DRAFT', max_length=20)),
                ('html_content', models.TextField(help_text='HTML email content')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='brands.brand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
