# Generated by Django 6.1 on 2026-08-22 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0016_apilog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('FULFILLMENT', 'Fulfillment & Orders'), ('SUPPORT', 'Customer Support')], default='SUPPORT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='brands.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('brand', 'user')},
            },
        ),
    ]
