# Generated by Django 6.1 on 2026-08-22 06:42

from django.db import migrations


def copy_owners_to_staff(apps, schema_editor):
    Brand = apps.get_model('brands', 'Brand')
    BrandStaff = apps.get_model('brands', 'BrandStaff')
    
    for brand in Brand.objects.all():
        if brand.owner:
            BrandStaff.objects.get_or_create(
                brand=brand,
                user=brand.owner,
                defaults={'role': 'OWNER'}
            )

def reverse_copy(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0017_brandstaff'),
    ]

    operations = [
        migrations.RunPython(copy_owners_to_staff, reverse_copy),
    ]
