# Generated by Django 6.1 on 2026-08-22 08:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0018_auto_20260822_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='b2b_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Global B2B discount percentage for wholesale customers', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='brand',
            name='enable_gift_cards',
            field=models.BooleanField(default=False, help_text='Enable gift card sales in this store'),
        ),
    ]
