# Generated by Django 6.1 on 2026-08-30 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0020_brand_seo_description_brand_seo_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_styles', models.JSONField(blank=True, default=dict, help_text='Colors, typography, spacing variables')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='brands.brand')),
            ],
        ),
        migrations.CreateModel(
            name='StorefrontSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('products', 'Product Grid'), ('collections', 'Collections'), ('categories', 'Categories'), ('header', 'Header / Navbar'), ('footer', 'Footer'), ('testimonials', 'Testimonials'), ('custom_html', 'Custom HTML'), ('newsletter', 'Newsletter Form'), ('announcement', 'Announcement Bar')], max_length=50)),
                ('name', models.CharField(blank=True, help_text='Optional internal name for the section', max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Text content, background images, specific tweaks')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='brands.storefrontlayout')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
