# Generated by Django 6.1 on 2026-08-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0021_storefrontlayout_storefrontsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='brands.brand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
