# Generated by Django 6.1 on 2026-08-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0022_brandcontactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefrontsection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('products', 'Product Grid'), ('collections', 'Collections'), ('categories', 'Categories'), ('header', 'Header / Navbar'), ('footer', 'Footer'), ('testimonials', 'Testimonials'), ('custom_html', 'Custom HTML'), ('newsletter', 'Newsletter Form'), ('announcement', 'Announcement Bar'), ('slideshow', 'Slideshow'), ('gallery', 'Gallery'), ('video', 'Video'), ('image_with_text', 'Image with Text'), ('text_columns', 'Text Columns'), ('countdown', 'Countdown'), ('rich_text', 'Rich Text'), ('logo_list', 'Logo List'), ('features', 'Features'), ('faq', 'FAQ'), ('blog_posts', 'Blog Posts')], max_length=50),
        ),
    ]
