# Generated by Django 6.1 on 2026-09-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0023_alter_storefrontsection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='e.g. shop.mybrand.com', max_length=255, null=True),
        ),
    ]
